### ISSUE TITLE
Don't get metrics

### ISSUE THREAD

**Issue by kvs96** [heubeck/statuspage-prometheus-exporter#2]
Hello

I tried using your docker image to track github status.

But unfortunately I don't get metrics:
<img width="1191" alt="Снимок экрана 2022-03-27 в 15 36 05" src="https://user-images.githubusercontent.com/92970666/160281621-322fbb2a-9e27-49f2-b74b-c430aef9329a.png">

Please tell me how can I fix this?

**Comment by heubeck** [comment]
Ugh... haven't maintained this component for quite a while...
How did you start/deploy it? (helm-chart, locally with/without docker).

Have you provided it a configuration with statuspage urls?
Can you please add the log output of the component itself?

**Comment by kvs96** [comment]
Thanks for the answer :)

Deployed to docker using your dockerfile - src/main/docker/Dockerfile.native 

Page available at http://185.125.90.7:8080/metrics

logs:
$ docker logs -f hungry_antonelli
Starting with configuration at 
cat: '': No such file or directory
2022-03-27 12:38:44,915 INFO  [io.quarkus] (main) status-metrics-exporter 0.0.1 native (powered by Quarkus 1.6.0.Final) started in 0.026s. Listening on: http://0.0.0.0:8080
2022-03-27 12:38:44,915 INFO  [io.quarkus] (main) Profile prod activated. 
2022-03-27 12:38:44,915 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, mutiny, scheduler, smallrye-context-propagation, vertx, vertx-web]


"Have you provided it a configuration with statuspage urls?" - unfortunately I don't understand what I should have done

I tried specifying the address of githubstatus in config.json before building the image:
<img width="654" alt="Снимок экрана 2022-03-27 в 18 58 15" src="https://user-images.githubusercontent.com/92970666/160290052-023a40b5-eb70-4fe6-9aba-b0a8c88483a5.png">

**Comment by heubeck** [comment]
Yeah, sorry for the not existing docs...

The component uses a configuration file, that need to be mounted into the container an announced by an env var: https://github.com/heubeck/statuspage-prometheus-exporter/blob/master/charts/statuspage-prometheus-exporter/templates/Deployment.yaml#L35

An example config file is here: https://github.com/heubeck/statuspage-prometheus-exporter/blob/master/config.json

Please let me know, how it goes...

**Comment by kvs96** [comment]
Thank you very much! It's all right!

<img width="768" alt="Снимок экрана 2022-03-29 в 21 27 57" src="https://user-images.githubusercontent.com/92970666/160680359-063e039a-4685-4c55-a84c-b1d793136484.png">

**Comment by heubeck** [comment]
awesome, thank you @kvs96 
if you find this component useful and continue to use it, please let me know - than I try to maintain it a bit ;)
